# Generated by Django 2.2.7 on 2019-11-22 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='posttag',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='posttag',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='posttag',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
