# Generated by Django 2.2.7 on 2019-12-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
    ]
